name: Node Continuous Integration

on: push

jobs:
  build:
    name: Lint, Build, Test,  Lib & Demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Build library
        run: npm run build:lib
      - name: Build demo app
        run: npm run build:demo
      - name: Test library
        run: npm run test:lib -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: Test demo app
        run: npm run test:demo -- --no-watch --no-progress --browsers=ChromeHeadlessCI
